environement:
  property: I AM THE DEFAULT

logging:
  level:
    ROOT: INFO
    com.example: DEBUG

server:
  port: 8080

spring:
  application:
    name: movieapi
  datasource:
    url: jdbc:h2:mem:movieapi
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  h2:
    console.enabled: true # Access to H2 Console  http://localhost:8080/h2-console
    console.path: /h2-console
    console.settings.trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

security:
  basic:
    enabled: true
    authorize-mode: NONE

omdbapi:
  url: http://www.omdbapi.com/
  apikey: c732beed

jwt:
  secret: mySecret


